apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab
  name: gitlab
spec:
  ports:
    - name: "8929"
      port: 8929
      targetPort: 8929
    - name: "2224"
      port: 2224
      targetPort: 22
  selector:
    io.kompose.service: gitlab
status:
  loadBalancer: {}
