apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim2
  labels:
    usage: monitoring
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
