apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    usage: monitoring
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
status:
  loadBalancer: {}
