apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
          - name: influxdb
            image: influxdb:2.4
            ports:
              - containerPort: 8086
            resources: {}
            volumeMounts:
              - mountPath: /imports
                name: influxdb-claim0
              - mountPath: /var/lib/influxdb
                name: influxdb-data
      restartPolicy: Always
      volumes:
        - name: influxdb-claim0
          persistentVolumeClaim:
            claimName: influxdb-claim0
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data
status: {}
