apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - env:
            - name: GF_INSTALL_PLUGINS
              valueFrom:
                configMapKeyRef:
                  key: GF_INSTALL_PLUGINS
                  name: configuration-env
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: GF_SECURITY_ADMIN_PASSWORD
                  name: configuration-env
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  key: GF_SECURITY_ADMIN_USER
                  name: configuration-env
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: INFLUXDB_ADMIN_PASSWORD
                  name: configuration-env
            - name: INFLUXDB_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  key: INFLUXDB_ADMIN_USER
                  name: configuration-env
            - name: INFLUXDB_DB
              valueFrom:
                configMapKeyRef:
                  key: INFLUXDB_DB
                  name: configuration-env
          image: influxdb:1.8-alpine
          name: influxdb
          ports:
            - containerPort: 8086
          resources: {}
          volumeMounts:
            - mountPath: /imports
              name: influxdb-claim0
            - mountPath: /var/lib/influxdb
              name: influxdb-data
      restartPolicy: Always
      volumes:
        - name: influxdb-claim0
          persistentVolumeClaim:
            claimName: influxdb-claim0
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data
status: {}
