apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf:1.24
          name: telegraf
          ports:
            - containerPort: 8125
              protocol: UDP
          resources: {}
      restartPolicy: Always
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
        - name: telegraf-claim0
          persistentVolumeClaim:
            claimName: telegraf-claim0
            readOnly: true
status: {}
