# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: telegraf-claim0
#   labels:
#     usage: monitoring
#   namespace: monitoring
# spec:
#   accessModes:
#     - ReadOnlyMany
#   resources:
#     requests:
#       storage: 100Mi
# status: {}
