# https://www.influxdata.com/blog/monitoring-kubernetes-architecture/
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  ports:
    - name: "8125"
      port: 8125
      protocol: UDP
      targetPort: 8125
  selector:
    io.kompose.service: telegraf
status:
  loadBalancer: {}
