# https://www.influxdata.com/blog/monitoring-kubernetes-architecture/
# https://www.gojek.io/blog/diy-set-up-telegraf-influxdb-grafana-on-kubernetes
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  namespace: monitoring
spec:
  ports:
    - name: "8125"
      port: 8125
      protocol: UDP
      targetPort: 8125
  selector:
    app: telegraf
status:
  loadBalancer: {}
