apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      name: grafana
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf:1.18-alpine
          name: telegraf
          ports:
            - containerPort: 8125
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-claim0
              subPath: telegraf.conf
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: telegraf-claim0
          persistentVolumeClaim:
            claimName: telegraf-claim0
            readOnly: true
          configMap:
            name: telegraf-config
status: {}
