#https://www.influxdata.com/blog/monitoring-kubernetes-architecture/
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |+
    [[outputs.influxdb_v2]]
      urls = ["http://localhost:8086"]
      token = "Sps-I98Prr8oxmZy0dgEUxf8Dihq9FbMhB7tZOC1Zv2-WRFsNkSHbDIgdcQMGaQzKbifLRR_UJ88E3VyeICdKw=="
      organization = "demo"
      bucket = "demo"
    # Statsd Server
    [[inputs.statsd]]
      max_tcp_connections = 250
      tcp_keep_alive = false
      service_address = ":8125"
      delete_gauges = true
      delete_counters = true
      delete_sets = true
      delete_timings = true
      metric_separator = "."
      allowed_pending_messages = 10000
      percentile_limit = 1000
      parse_data_dog_tags = true 
      read_buffer_size = 65535
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
    [[inputs.diskio]]
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    [[inputs.swap]]
    [[inputs.system]]
    [[inputs.prometheus]]
      urls = ["http://localhost:9100/metrics"]
    [[inputs.kubernetes]]
      url = "http://1.1.1.1:10255"
    [[inputs.http_listener_v2]]
      ## Address and port to host HTTP listener on
      service_address = ":1234"
      ## Path to listen to.
      path = "/receive"
      ## Data format to consume.
      data_format = "prometheusremotewrite"